
export const publications = [
  {
    id: 1,
    title: "Wave Resistance Prediction",
    author: "L. Larsson",
    year: 2023,
    journal: "Journal of Ship Research",
    citations: 142,
    color: "from-blue-600 via-blue-700 to-blue-900",
    accent: "bg-blue-400",
    category: "CFD",
    abstract:
      "Advanced wave resistance computation using panel methods with nonlinear free-surface boundary conditions applied to modern hull forms.",
  },
  {
    id: 2,
    title: "Viscous Flow Computation",
    author: "B. Regnström",
    year: 2022,
    journal: "Ocean Engineering",
    citations: 98,
    color: "from-emerald-600 via-emerald-700 to-emerald-900",
    accent: "bg-emerald-400",
    category: "RANS",
    abstract:
      "RANS-based viscous flow solver validation against experimental data for tanker and container ship hull forms.",
  },
  {
    id: 3,
    title: "Hull Optimization Methods",
    author: "C. Janson",
    year: 2022,
    journal: "Applied Ocean Research",
    citations: 76,
    color: "from-violet-600 via-violet-700 to-violet-900",
    accent: "bg-violet-400",
    category: "Optimization",
    abstract:
      "Parametric hull form optimization using adjoint methods coupled with potential flow solvers for minimum resistance.",
  },
  {
    id: 4,
    title: "Free-Surface Panel Methods",
    author: "L. Larsson",
    year: 2021,
    journal: "Computers & Fluids",
    citations: 189,
    color: "from-amber-600 via-amber-700 to-amber-900",
    accent: "bg-amber-400",
    category: "CFD",
    abstract:
      "Higher-order panel method for free-surface flows with improved convergence properties and accuracy benchmarks.",
  },
  {
    id: 5,
    title: "Propeller-Hull Interaction",
    author: "A. Hellsten",
    year: 2021,
    journal: "Marine Technology",
    citations: 64,
    color: "from-rose-600 via-rose-700 to-rose-900",
    accent: "bg-rose-400",
    category: "RANS",
    abstract:
      "Coupled RANS-BEM approach for self-propulsion simulation including rudder effects and energy-saving devices.",
  },
  {
    id: 6,
    title: "Turbulence Modeling in CFD",
    author: "B. Regnström",
    year: 2020,
    journal: "Int. J. Numerical Methods",
    citations: 113,
    color: "from-cyan-600 via-cyan-700 to-cyan-900",
    accent: "bg-cyan-400",
    category: "RANS",
    abstract:
      "Comparative study of EASM and k-ω SST turbulence models for ship stern flow prediction accuracy.",
  },
  {
    id: 7,
    title: "Resistance Scaling Laws",
    author: "C. Janson",
    year: 2020,
    journal: "Ship Technology Research",
    citations: 87,
    color: "from-indigo-600 via-indigo-700 to-indigo-900",
    accent: "bg-indigo-400",
    category: "Optimization",
    abstract:
      "Revised form-factor methods for resistance extrapolation from model to full scale using CFD corrections.",
  },
  {
    id: 8,
    title: "Grid Generation Techniques",
    author: "L. Larsson",
    year: 2019,
    journal: "J. Computational Physics",
    citations: 55,
    color: "from-teal-600 via-teal-700 to-teal-900",
    accent: "bg-teal-400",
    category: "CFD",
    abstract:
      "Automatic grid generation strategies for complex ship geometries with boundary layer resolution control.",
  },
];